#Full path: /var/www/lab_app/lab_app_uwsgi.ini

[uwsgi]
#application's base folder
base = /var/www/lab_app

master = true 

#add this at handoff 
uid = lab_app_user
gid = lab_app_user

#python module to import
app = main
module = %(app)

# testing: comment these out - let 'uv run' handle this natively now,
# in systemd dervice file ->  '[service]'
#home = %(base)/.venv
#virtualenv = %(base)/.venv
#pythonpath = %(base)

#socket file's location

#old socket location
#socket = /var/www/lab_app/%n.sock

#new socket location with lab_app_user:www-data 750 permissions (better) 
#%n.sock will auto-eval to 'my_app' in system call: 'uwsgi --ini /etc/uwsgi/my_app.ini'
socket = /var/www/run/uwsgi/lab_app/%n.sock


#permissions for the socket file
#add this at handoff
chown-socket = lab_app_user:www-data
#chmod-socket    = 666
chmod-socket    = 660

#add this at handoff?
vacuum = true

#the variable that holds a flask application inside the module imported at line #6
callable = app

#location of log files
#logto = /var/log/uwsgi/%n.log
logto = /var/log/uwsgi/lab_app_uwsgi.log
######################################################
######################################################

